# Generated by Django 5.2.5 on 2026-02-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot_enabled', models.BooleanField(default=True, verbose_name='Bot faolmi')),
                ('bot_token', models.CharField(help_text='Telegram bot token', max_length=255, verbose_name='Bot Token')),
                ('max_file_size_mb', models.PositiveIntegerField(default=50, verbose_name='Maksimal fayl hajmi (MB)')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=10, verbose_name="Har minutda maksimal so'rovlar")),
                ('maintenance_message', models.TextField(blank=True, verbose_name='Texnik xizmat xabari')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='Texnik xizmat rejimi')),
            ],
            options={
                'verbose_name': 'Bot sozlamalari',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Rasm')),
                ('send_type', models.CharField(choices=[('once', 'Bir marta'), ('repeat', 'Takroriy')], default='once', max_length=10, verbose_name='Yuborish turi')),
                ('repeat_hours', models.PositiveIntegerField(default=0, help_text='Faqat takroriy yuborish uchun', verbose_name='Har necha soatda (takroriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='pending', max_length=10, verbose_name='Holat')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Yuborilganlar soni')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Xatoliklar soni')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi yuborilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklashlar soni')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Bloklangan')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='ShazamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_name', models.CharField(max_length=255, verbose_name='Audio fayl nomi')),
                ('recognized_title', models.CharField(blank=True, max_length=500, null=True, verbose_name="Aniqlangan qo'shiq")),
                ('recognized_artist', models.CharField(blank=True, max_length=500, null=True, verbose_name='Aniqlangan ijrochi')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Muvaffaqiyatli')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('recognized_at', models.DateTimeField(auto_now_add=True, verbose_name='Aniqlangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shazam_logs', to='core.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Shazam log',
                'verbose_name_plural': 'Shazam loglar',
                'ordering': ['-recognized_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name="Qidiruv so'rovi")),
                ('results_count', models.IntegerField(default=0, verbose_name='Natijalar soni')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Qidirilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='core.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qidiruv tarixi',
                'verbose_name_plural': 'Qidiruv tarixi',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500, verbose_name='Video havolasi')),
                ('video_title', models.CharField(max_length=500, verbose_name='Video nomi')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('likee', 'Likee'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Platforma')),
                ('format_label', models.CharField(max_length=50, verbose_name='Format')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Ishlanmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Fayl hajmi (bayt)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xatolik xabari')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='core.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuklash tarixi',
                'verbose_name_plural': 'Yuklash tarixi',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
