# Generated by Django 5.2.5 on 2026-02-10 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kampaniya nomi')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='Rasm')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni')),
                ('button_url', models.URLField(blank=True, verbose_name='Tugma havolasi')),
                ('target_audience', models.CharField(choices=[('all', 'Hammasi'), ('premium', 'Premium'), ('free', 'Bepul')], default='all', max_length=10, verbose_name='Maqsadli auditoriya')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejalashtirish vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', 'Rejalashtirilgan'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='draft', max_length=10)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklama kampaniyasi',
                'verbose_name_plural': 'Reklama kampaniyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(verbose_name='Muddat (kun)')),
                ('daily_download_limit', models.PositiveIntegerField(default=100)),
                ('daily_shazam_limit', models.PositiveIntegerField(default=50)),
                ('max_file_size_mb', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Premium reja',
                'verbose_name_plural': 'Premium rejalar',
            },
        ),
        migrations.AddField(
            model_name='botsettings',
            name='ad_revenue_per_view',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Reklama daromadi (koʻrishga)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='free_daily_download_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='Bepul kunlik yuklab olish limiti'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='instagram_enabled',
            field=models.BooleanField(default=True, verbose_name='Instagram yoqilganmi'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='likee_enabled',
            field=models.BooleanField(default=True, verbose_name='Likee yoqilganmi'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='parallel_download_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='Parallel yuklab olish limiti'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='premium_daily_download_limit',
            field=models.PositiveIntegerField(default=100, verbose_name='Premium kunlik yuklab olish limiti'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='shazam_daily_limit',
            field=models.PositiveIntegerField(default=20, verbose_name='Shazam kunlik limit'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='shazam_max_audio_length',
            field=models.PositiveIntegerField(default=60, verbose_name='Shazam maks audio uzunligi (soniya)'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='snapchat_enabled',
            field=models.BooleanField(default=True, verbose_name='Snapchat yoqilganmi'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='tiktok_enabled',
            field=models.BooleanField(default=True, verbose_name='TikTok yoqilganmi'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='youtube_enabled',
            field=models.BooleanField(default=True, verbose_name='YouTube yoqilganmi'),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('api_error', 'API xatolik'), ('download_error', 'Yuklash xatoligi'), ('shazam_error', 'Shazam xatoligi'), ('webhook_error', 'Webhook xatoligi'), ('system_error', 'Tizim xatoligi')], max_length=20)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Xatolik logi',
                'verbose_name_plural': 'Xatolik loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_user', to='core.telegramuser')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='core.telegramuser')),
            ],
            options={
                'verbose_name': 'Referal statistikasi',
                'verbose_name_plural': 'Referal statistikalari',
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
    ]
