# Generated by Django 5.2.5 on 2026-02-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Rasm')),
                ('send_type', models.CharField(choices=[('once', 'Bir marta'), ('repeat', 'Takroriy')], default='once', max_length=10, verbose_name='Yuborish turi')),
                ('repeat_hours', models.PositiveIntegerField(default=0, help_text='Faqat takroriy yuborish uchun', verbose_name='Har necha soatda (takroriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='pending', max_length=10, verbose_name='Holat')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Yuborilganlar soni')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Xatoliklar soni')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi yuborilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500, verbose_name='Video havolasi')),
                ('video_title', models.CharField(max_length=500, verbose_name='Video nomi')),
                ('format_label', models.CharField(max_length=50, verbose_name='Format')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='bot.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuklash tarixi',
                'verbose_name_plural': 'Yuklash tarixi',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
