# Generated by Django 5.2.5 on 2026-02-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_broadcast_downloadhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broadcast',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='DownloadHistory',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
